#! /bin/bash

__mods() {
    go list -m -f '{{if not (or .Indirect .Main)}}{{.Path}}{{end}}' all
}

__modctl_complete() {
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case "$cur" in
        "upgrade")
            opts="--help";;
        u*)
            opts=("upgrade");;
        "")
            case "$prev" in
                "upgrade")
                    opts="$(__mods '') --help";;
                "modctl")
                    opts="--help upgrade";;
        esac;;
        *)
            case "$prev" in
                "upgrade")
                    opts="$(__mods $cur)" #git repos
        esac;;
    esac
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return
}

complete -F __modctl_complete modctl