#! /bin/bash

__mods() {
    modctl list-modules | grep "$1" | sed s/$/@/g
}

__modctl_complete() {
    compopt +o nospace
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    case "$cur" in
        "upgrade")
            opts="--help";;
        u*)
            opts=("upgrade");;
        "")
            case "$prev" in
                "upgrade")
                    opts="go@ $(__mods '') --help";;
                "modctl")
                    opts="--help upgrade";;
        esac;;
        *)
            case "$prev" in
                "upgrade")
                    compopt -o nospace
                    opts="go@ $(__mods $cur)" #git repos
        esac;;
    esac
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return
}

complete -F __modctl_complete modctl